include!("core_handlers/base.rs");
include!("core_handlers/internal_metrics.rs");
include!("core_handlers/account_access.rs");
include!("core_handlers/account_tenant_admin.rs");
include!("core_handlers/model_routing_admin.rs");
include!("core_handlers/ai_error_learning.rs");
include!("core_handlers/billing_runtime.rs");
include!("core_handlers/models_probe.rs");
include!("core_handlers/upstream_health.rs");
